server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url:
        databaseName: mycellar
        serverName: localhost
        username: mycellar
        password: mYcEll@r!2016

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false


    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: mycellar

http:
    cache:
        timeToLiveInDays: 31

mail:
    host: smtp.gmail.com
    port: 587
    username: mycellar.app@gmail.com
    password: mYcEll@r!2016
    protocol: smtp
    from: mycellar.app@gmail.com
    smtp.auth: true
    smtp.starttls.enable: true
    smtp.starttls.required: true
    smtp.timeout: 8500
    smtp.ssl.trust: smtp.gmail.com


